[workspace]
resolver = "2"
members = [
    "authly-core",
    "authly-flow",
    "authly-session",
    "authly-token",
    "authly-providers-github",
    "authly-providers-google",
    "authly-providers-discord",
    "authly-axum",
]
