[package]
name = "authly-token"
version = "0.1.0"
edition = "2021"

[dependencies]
authly-core = { path = "../authly-core" }
jsonwebtoken = "9.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
chrono = { version = "0.4", features = ["serde"] }
