name: Publish Rust Crates to crates.io

on:
  workflow_dispatch:
  release:
    types: [created]

jobs:
  publish:
    name: publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable

      - name: Login to crates.io
        run: cargo login ${{ secrets.CARGO_REGISTRY_TOKEN }}

      - name: Publish authly-core
        run: cargo publish --package authly-core --token ${{ secrets.CARGO_REGISTRY_TOKEN }}

      - name: Publish authly-token
        run: cargo publish --package authly-token --token ${{ secrets.CARGO_REGISTRY_TOKEN }}

      - name: Publish authly-session
        run: cargo publish --package authly-session --token ${{ secrets.CARGO_REGISTRY_TOKEN }}

      - name: Publish authly-oidc
        run: cargo publish --package authly-oidc --token ${{ secrets.CARGO_REGISTRY_TOKEN }}

      - name: Publish authly-flow
        run: cargo publish --package authly-flow --token ${{ secrets.CARGO_REGISTRY_TOKEN }}

      - name: Publish authly-actix
        run: cargo publish --package authly-actix --token ${{ secrets.CARGO_REGISTRY_TOKEN }}

      - name: Publish authly-axum
        run: cargo publish --package authly-axum --token ${{ secrets.CARGO_REGISTRY_TOKEN }}

      - name: Publish authly-providers-discord
        run: cargo publish --package authly-providers-discord --token ${{ secrets.CARGO_REGISTRY_TOKEN }}

      - name: Publish authly-providers-github
        run: cargo publish --package authly-providers-github --token ${{ secrets.CARGO_REGISTRY_TOKEN }}

      - name: Publish authly-providers-google
        run: cargo publish --package authly-providers-google --token ${{ secrets.CARGO_REGISTRY_TOKEN }}
